version: "3.3"
services:
    moleculeIPC_driver:
        image: "${MOLECULEIPC_DRIVER_IMAGE:-moleculeIPC_driver_image}"
        volumes:
            - "/tmp/fifo_dir/:/tmp/fifo_dir"
        environment: 
            FUNC_NAME: moleculeIPC_driver
            NEXT_FUNC: moleculeIPC_mapper
            IPC_UUID: ${MOLECULEIPC_DRIVER_IPC_UUID}
            NEXT_UUID: ${MOLECULEIPC_MAPPER_IPC_UUID}
        network_mode: "host"
        ipc: host

    moleculeIPC_mapper:
        image: "${MOLECULEIPC_MAPPER_IMAGE:-moleculeIPC_mapper_image}"
        volumes:
            - "/tmp/fifo_dir/:/tmp/fifo_dir"
        environment: 
            FUNC_NAME: moleculeIPC_mapper
            NEXT_FUNC: moleculeIPC_reducer
            IPC_UUID: ${MOLECULEIPC_MAPPER_IPC_UUID}
            NEXT_UUID: ${MOLECULEIPC_REDUCER_IPC_UUID}
        network_mode: "host"
        ipc: host

    moleculeIPC_reducer:
        image: "${MOLECULEIPC_REDUCER_IMAGE:-moleculeIPC_reducer_image}"
        volumes:
            - "/tmp/fifo_dir/:/tmp/fifo_dir"
        environment: 
            FUNC_NAME: moleculeIPC_reducer
            IPC_UUID: ${MOLECULEIPC_REDUCER_IPC_UUID}
        network_mode: "host"
        ipc: host
            